CREATE OR REPLACE DATABASE FINAL_PASSENGER;
USE DATABASE FINAL_PASSENGER;

CREATE OR REPLACE SCHEMA ANALYTICS;
USE SCHEMA ANALYTICS;

USE DATABASE FINAL_PASSENGER;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE RAW_PASSENGER_DATA (
    DATE DATE,
    CARRIER STRING,
    SERVICE_TYPE STRING,
    DEPARTURES INT,
    PASSENGERS INT,
    PERCENT_OF_2019 FLOAT,
    MONTH STRING,
    YEAR INT,
    WEEK_NUMBER INT,
    WEATHER_SCORE FLOAT,
    FUEL_PRICE FLOAT,
    HOLIDAY_FLAG STRING
);


CREATE OR REPLACE FILE FORMAT CSV_DDMMYYYY
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
DATE_FORMAT = 'DD/MM/YYYY'
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('', 'NULL');



CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    FULL_DATE DATE,
    YEAR INT,
    MONTH INT,
    WEEK_NUMBER INT
);


CREATE OR REPLACE TABLE DIM_CARRIER (
    CARRIER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CARRIER STRING
);

CREATE OR REPLACE TABLE DIM_SERVICE_TYPE (
    SERVICE_TYPE_KEY INT AUTOINCREMENT PRIMARY KEY,
    SERVICE_TYPE STRING
);


CREATE OR REPLACE TABLE DIM_EXTERNAL_FACTORS (
    FACTOR_KEY INT AUTOINCREMENT PRIMARY KEY,
    WEATHER_SCORE FLOAT,
    FUEL_PRICE FLOAT,
    HOLIDAY_FLAG STRING
);

CREATE OR REPLACE TABLE FACT_RIDERSHIP (
    DATE_KEY INT,
    CARRIER_KEY INT,
    SERVICE_TYPE_KEY INT,
    FACTOR_KEY INT,
    PASSENGERS INT,
    DEPARTURES INT,
    PERCENT_OF_2019 FLOAT,
    
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (CARRIER_KEY) REFERENCES DIM_CARRIER(CARRIER_KEY),
    FOREIGN KEY (SERVICE_TYPE_KEY) REFERENCES DIM_SERVICE_TYPE(SERVICE_TYPE_KEY),
    FOREIGN KEY (FACTOR_KEY) REFERENCES DIM_EXTERNAL_FACTORS(FACTOR_KEY)
);

SHOW DATABASES;
SHOW SCHEMAS;
SHOW TABLES IN DATABASE final_passenger;


USE DATABASE FINAL_PASSENGER;
USE SCHEMA ANALYTICS;

SHOW TABLES;


INSERT INTO DIM_CARRIER (CARRIER)
SELECT DISTINCT CARRIER
FROM RAW_PASSENGER_DATA;

INSERT INTO DIM_SERVICE_TYPE (SERVICE_TYPE)
SELECT DISTINCT SERVICE_TYPE
FROM RAW_PASSENGER_DATA;

INSERT INTO DIM_EXTERNAL_FACTORS (WEATHER_SCORE, FUEL_PRICE, HOLIDAY_FLAG)
SELECT DISTINCT WEATHER_SCORE, FUEL_PRICE, HOLIDAY_FLAG
FROM RAW_PASSENGER_DATA;


INSERT INTO DIM_DATE (DATE_KEY, FULL_DATE, YEAR, MONTH, WEEK_NUMBER)
SELECT DISTINCT
    TO_VARCHAR(DATE, 'YYYYMMDD')::INT AS DATE_KEY,
    DATE,
    YEAR::INT,
    TRY_TO_NUMBER(MONTH) AS MONTH,   -- convert string → number
    WEEK_NUMBER::INT
FROM RAW_PASSENGER_DATA;


INSERT INTO FACT_RIDERSHIP (
    DATE_KEY, CARRIER_KEY, SERVICE_TYPE_KEY, FACTOR_KEY,
    PASSENGERS, DEPARTURES, PERCENT_OF_2019
)
SELECT
    TO_VARCHAR(R.DATE, 'YYYYMMDD')::INT AS DATE_KEY,
    C.CARRIER_KEY,
    S.SERVICE_TYPE_KEY,
    F.FACTOR_KEY,
    R.PASSENGERS,
    R.DEPARTURES,
    R."PERCENT_OF_2019"
FROM RAW_PASSENGER_DATA R
JOIN DIM_CARRIER C 
    ON R.CARRIER = C.CARRIER
JOIN DIM_SERVICE_TYPE S 
    ON R.SERVICE_TYPE = S.SERVICE_TYPE
JOIN DIM_EXTERNAL_FACTORS F 
    ON R.WEATHER_SCORE = F.WEATHER_SCORE
   AND R.FUEL_PRICE = F.FUEL_PRICE
   AND R.HOLIDAY_FLAG = F.HOLIDAY_FLAG;

SELECT COUNT(*) FROM FACT_RIDERSHIP;
SELECT * FROM FACT_RIDERSHIP LIMIT 20;

SHOW TABLES;

SELECT * FROM DIM_CARRIER;

SELECT * FROM DIM_DATE;

SELECT * FROM DIM_EXTERNAL_FACTORS;

SELECT * FROM DIM_SERVICE_TYPE;

SELECT * FROM FACT_RIDERSHIP;